### PR TITLE
Added support for enum (as generator and in class builder)

### LINKED ISSUE #46: EnumBuilder
Can Enum types be generated? Quid an "EnumBuilder" ?

### PR DESCRIPTION
**Pull request by MilleBo**
Fix #46

### CODE REVIEW

**Comment by MilleBo** [comment]
Oh that's true (we should add support for values). I will update the PR later with this + support for attributes.

> Does the code allow the generation of Enums not in scope of a class?

Currently no as the ClassBuilder always put everything inside the class. But I could add a NamespaceBuilder if you want? Then you can at least make a seperate file with just namespace + enums. 

It would require a bit more work to get namespace + class + enum outside class. But I can add that later on too of course.

**Comment by Illeris** [comment]
> Oh that's true (we should add support for values). I will update the PR later with this + support for attributes.
> 
> > Does the code allow the generation of Enums not in scope of a class?
> 
> Currently no as the ClassBuilder always put everything inside the class. But I could add a NamespaceBuilder if you want? Then you can at least make a seperate file with just namespace + enums.
> 
> It would require a bit more work to get namespace + class + enum outside class. But I can add that later on too of course.

Would be nice to have them separated. Enables easier search for them in compiled code (for sync operation between external model/platform definition & code). If you need help on the coding, I could add them too.

**Comment by MilleBo** [comment]
It should be fine! Should have them done tonight.

**Comment by MilleBo** [comment]
There we go. Had to refactor a bit around the builders but now we support enum member values and attributes and a new namespacebuilder so you can create namespaces with enum outside of classes.

**Pull request merged**
